# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: knanne
author: Kain Nanne
email: kain.nanne@gmail.com
description: Expert traveler, amateur farmer, beer / wine enthusiast - with a data science problem

avatar: "/assets/img/ic_android_black_24dp_2x.ico"
logo: "/assets/img/ic_android_black_24dp_2x.ico"

twitter_username: knanne
github_username: knanne
linkedin_username: kainnanne

twitter:
  username: knanne

social:
  name: Kain Nanne
  links:
    - https://twitter.com/knanne
    - https://www.linkedin.com/in/kainnanne
    - https://plus.google.com/+kainnanne
    - https://github.com/knanne
    - https://keybase.io/knanne

google_analytics: UA-90589325-1

disqus:
  active: False # NOT in use (see Google Plus Comments)
  shortname: knanne

baseurl: "" # root of site, e.g. /blog
url: "https://knanne.github.io" # https://knanne.github.io

nbviewer: "http://nbviewer.jupyter.org/github/knanne/knanne.github.io/blob/master/notebooks"

nav-links:
  About: "about"
  Posts: "posts"
  Projects: "projects"

# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      is_post: True # used in _includes/foot_scripts.html to dynamically load scripts
      layout: "post"
      author: Kain Nanne
      share: True # include social sharing buttons
      comments: True # include comments section
  -
    scope:
      path: "_drafts"
    values:
      is_post: True # used in _includes/foot_scripts.html to dynamically load scripts
      layout: "post"
      author: Kain Nanne
      share: False # hide social sharing buttons
      comments: False # hide comments section
      is_draft: True # used in _layouts/post.html to show draft alert
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "page"

# https://jekyllrb.com/docs/collections/
collections:
  posts:
    permalink: /posts/:slug
  projects:
    output: True
    permalink: /projects/:title

excerpt_separator: <!-- excerpt separator -->

theme: minima

sass:
  sass_dir: _sass # @import "minima" comes from gem
  style: compressed

markdown: kramdown
kramdown:
  toc_levels: 1..1 #1..2 # only using h1 thru h2 to generate table of contents in posts

highlighter: rouge

ampdir: amp

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - amp-jekyll
  - html-proofer
  - jekyll-last-modified-at
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
  - vendor
